/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/seller": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.seller.id"];
          user?: parameters["rowFilter.seller.user"];
          earned?: parameters["rowFilter.seller.earned"];
          created_at?: parameters["rowFilter.seller.created_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["seller"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** seller */
          seller?: definitions["seller"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.seller.id"];
          user?: parameters["rowFilter.seller.user"];
          earned?: parameters["rowFilter.seller.earned"];
          created_at?: parameters["rowFilter.seller.created_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.seller.id"];
          user?: parameters["rowFilter.seller.user"];
          earned?: parameters["rowFilter.seller.earned"];
          created_at?: parameters["rowFilter.seller.created_at"];
        };
        body: {
          /** seller */
          seller?: definitions["seller"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  seller: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: jsonb */
    user: unknown;
    /** Format: real */
    earned: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
  };
}

export interface parameters {
  /** @description Preference */
  preferParams: "params=single-object";
  /** @description Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** @description Preference */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description seller */
  "body.seller": definitions["seller"];
  /** Format: bigint */
  "rowFilter.seller.id": string;
  /** Format: jsonb */
  "rowFilter.seller.user": string;
  /** Format: real */
  "rowFilter.seller.earned": string;
  /** Format: timestamp with time zone */
  "rowFilter.seller.created_at": string;
}

export interface operations {}

export interface external {}
